#!/usr/bin/env bash

export DRUNKMODE=1

# Set DRUNKMODE env variable on
echo 'export DRUNKMODE=1' > ~/.drunkmoderc

# Write the new safer command replacements to drunkmoderc
cat ~/.drunk_commands >> ~/.drunkmoderc

# (won't be reflected in parent process anyway)
#source ~/.drunkmoderc

# Check if the environment variable is actually correctly set to on (but still
# actually for this process, not parent)
[ $DRUNKMODE==1 ] && echo 'Drunkmode ON' || echo 'No, something went wrong! Drunkmode is OFF!'

# Note: dirty/problematic trick to source to set the DRUNKMODE env variable in  
# the calling shell.
exec bash

